version: '3.8'
# based on https://github.com/testdrivenio/fastapi-sqlmodel-alembic

services:

  sqlmodel:
    image: uvicorn
    command: uvicorn fastapi_playground.sqlmodel.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_playground:/usr/src/app/fastapi_playground
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/foo
    depends_on:
      - db
      - fastapi  # just need Docker image `uvicorn` to be build but in docker-compose it is not possible to build image without running container

  fastapi:
    build: ./docker/sqlmodel
    image: uvicorn
    command: uvicorn fastapi_playground.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_playground:/usr/src/app/fastapi_playground
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/foo
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
