version: 1
formatters:
  simple:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no
  uvicorn:
    level: INFO
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: INFO
    propagate: False

root:
  level: DEBUG
  handlers: [console]
