"""middle name

Revision ID: 1fd16234d9b3
Revises: 1a2dceac630c
Create Date: 2023-08-07 04:10:46.369615

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '1fd16234d9b3'
down_revision = '1a2dceac630c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_middle_name'), 'user', ['middle_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_middle_name'), table_name='user')
    op.drop_column('user', 'middle_name')
    # ### end Alembic commands ###
