"""autogenerate

Revision ID: f960b0d38cce
Revises: 1fd16234d9b3
Create Date: 2023-08-07 04:19:23.582061

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'f960b0d38cce'
down_revision = '1fd16234d9b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
